### ISSUE TITLE
请问这是论文代码吗？

### ISSUE THREAD

**Issue by huangsheng97** [jerrywn121/Arctic_SIC_prediction#1]
我发现有一篇未公开代码的论文方法和这个很像
https://doi.org/10.3390/jmse9030330

**Comment by jerrywn121** [comment]
不是论文代码，也不是这个链接里面的论文的代码。。是我自己做的project。不过看了下链接里论文大纲，用的模型应该是一样的，都是ConvLSTM。

**Comment by huangsheng97** [comment]
感谢您的分享
