### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by muchen50** [jerrywn121/Arctic_SIC_prediction#2]
Hi, @jerrywn121 , I am ShiChen Zhu, a postgraduate in Tongji University.  And my current research are around Arctic Sea Ice. Since I can't find your contact information, i create an issue here.

I have learned a lot from your research and I want to duplicate your code. However, I encountered some problems in processing the data.  I was wondering if you could help me. By the way, have you ever written a paper on it?

Best wishes to you! I am looking forward to your reply!

**Comment by jerrywn121** [comment]
We can contact through my email jerrywn121@gmail.com. You can email me and I will give more information there.

**Comment by muchen50** [comment]
I am very glad to receive your reply. I want to reproduce your code, but I can't download the data due to network or other reasons.&nbsp;Therefore, I used my own data in .nc file format. However, there are many problems in processing data and training data, such as&nbsp;NetCDF: Not a valid ID.&nbsp;I wonder if you can provide your data to me so that I can run the code successfully. I really need your help! I am looking forward to your early reply!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jerrywn121/Arctic_SIC_prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月23日(星期三) 晚上9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jerrywn121/Arctic_SIC_prediction] Help (Issue #2)





 
We can contact through my email ***@***.*** And I can give more detailed information there~
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jerrywn121** [comment]
For the data, I think the first thing you can try is to try to download the data from 
https://nsidc.org/data/nsidc-0051 using the command line, with VPN. Using other sources of data is fine as long as the encoding format is the same (different data may have different filling values for missing values and also the image size and projections may also be different). If you want to read your own data of .nc format, I recommend you use xarray package and have installed other package dependencies (you can google for more information). If you really want the original data (and I have a report for this but no paper), you should write an email to me, but note that the data is a little outdated (as NSIDC may have fixed some bugs in previous data and provide more updated ones) for scientific research and you should download the data yourself for your own research.

**Comment by muchen50** [comment]
Thank you for your answer!&nbsp;I'm still learning, but I can't find the code to predict sea ice concentration in any of the papers I've seen.&nbsp;I think your code on Github will help me a lot.&nbsp;It's very kind of you to give me your report. Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jerrywn121/Arctic_SIC_prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 中午1:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jerrywn121/Arctic_SIC_prediction] Help (Issue #2)





 
For the data, I think the first thing you can try is to try to download the data from
 https://nsidc.org/data/nsidc-0051 using the command line, with VPN. Using other sources of data is fine as long as the encoding format is the same (different data may have different filling values for missing values and also the image size and projections may also be different). If you want to read your own data of .nc format, I recommend you use xarray package and have installed other package dependencies (you can google for more information). If you really want the original data (and I have a report for this but no paper), you should write an email to me, but note that the data is a little outdated (as NSIDC may have fixed some bugs in previous data and provide more updated ones) for scientific research and you should download the data yourself for your own research.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jerrywn121** [comment]
In case you want any materials (report or other things), you should write an email to me
